version = 0.1
[default.deploy.parameters]
stack_name = "sam-lambda-stack-83"
resolve_s3 = true
s3_prefix = "sam-lambda-stack-83"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
