AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam_lambda_project

  Lambda function to process input, generate content, and upload to S3.

Globals:
  Function:
    Timeout: 10
    MemorySize: 128
    LoggingConfig:
      LogFormat: JSON

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          BUCKET_NAME: pgr301-couch-explorers
          CANDIDATE_ID: "83"
      Policies:
        - S3CrudPolicy:
            BucketName: pgr301-couch-explorers
      Events:
        GenerateContentApi:
          Type: Api
          Properties:
            RestApiId: !Ref MyRegionalRestApi  # Updated ID reference
            Path: /generate
            Method: post

  MyRegionalRestApi:  # Updated logical ID
    Type: AWS::Serverless::Api
    Properties:
      Name: MyRegionalApi
      StageName: Prod
      EndpointConfiguration: REGIONAL

Outputs:
  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub "https://${MyRegionalRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/generate/"
  HelloWorldFunction:
    Description: Lambda Function ARN
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: Implicit IAM Role created for the Lambda function
    Value: !GetAtt HelloWorldFunctionRole.Arn
