AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam_lambda_project

  Lambda function to process input, generate content, and upload to S3.

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    LoggingConfig:
      LogFormat: JSON

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: image_generator/
      Handler: generate_image.lambda_handler  # Updated handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          BUCKET_NAME: pgr301-couch-explorers
          CANDIDATE_ID: "83"
      Policies:
        - S3CrudPolicy:
            BucketName: pgr301-couch-explorers
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource:
                - arn:aws:bedrock:us-east-1::foundation-model/amazon.titan-image-generator-v1
      Events:
        GenerateContentApi:
          Type: Api
          Properties:
            RestApiId: !Ref MyRegionalRestApi
            Path: /generate
            Method: post

MyRegionalRestApi:
  Type: AWS::Serverless::Api
  Properties:
    Name: MyRegionalApi-cand-83
    StageName: Prod
    EndpointConfiguration: REGIONAL



Outputs:
  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub "https://${MyRegionalRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/generate/"
  HelloWorldFunction:
    Description: Lambda Function ARN
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: Implicit IAM Role created for the Lambda function
    Value: !GetAtt HelloWorldFunctionRole.Arn
